/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as appAppRouteImport } from './routes/(app)/_app'
import { Route as appAppIndexRouteImport } from './routes/(app)/_app.index'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'
import { Route as appAppThesisProcessRouteImport } from './routes/(app)/_app.thesis-process'
import { Route as appAppScheduleRouteImport } from './routes/(app)/_app.schedule'
import { Route as appAppProjectEnrollmentRouteImport } from './routes/(app)/_app.project-enrollment'
import { Route as appAppThesisProcessIndexRouteImport } from './routes/(app)/_app.thesis-process.index'
import { Route as appAppProjectEnrollmentIndexRouteImport } from './routes/(app)/_app.project-enrollment.index'
import { Route as appAppThesisProcessProcessIdRouteImport } from './routes/(app)/_app.thesis-process.$processId'
import { Route as appAppProjectEnrollmentRoundIdRouteImport } from './routes/(app)/_app.project-enrollment.$roundId'
import { Route as appAppDefenseRoundIdRouteImport } from './routes/(app)/_app.defense.$roundId'

const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: '/(app)/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppIndexRoute = appAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const appAppThesisProcessRoute = appAppThesisProcessRouteImport.update({
  id: '/thesis-process',
  path: '/thesis-process',
  getParentRoute: () => appAppRoute,
} as any)
const appAppScheduleRoute = appAppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => appAppRoute,
} as any)
const appAppProjectEnrollmentRoute = appAppProjectEnrollmentRouteImport.update({
  id: '/project-enrollment',
  path: '/project-enrollment',
  getParentRoute: () => appAppRoute,
} as any)
const appAppThesisProcessIndexRoute =
  appAppThesisProcessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appAppThesisProcessRoute,
  } as any)
const appAppProjectEnrollmentIndexRoute =
  appAppProjectEnrollmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appAppProjectEnrollmentRoute,
  } as any)
const appAppThesisProcessProcessIdRoute =
  appAppThesisProcessProcessIdRouteImport.update({
    id: '/$processId',
    path: '/$processId',
    getParentRoute: () => appAppThesisProcessRoute,
  } as any)
const appAppProjectEnrollmentRoundIdRoute =
  appAppProjectEnrollmentRoundIdRouteImport.update({
    id: '/$roundId',
    path: '/$roundId',
    getParentRoute: () => appAppProjectEnrollmentRoute,
  } as any)
const appAppDefenseRoundIdRoute = appAppDefenseRoundIdRouteImport.update({
  id: '/defense/$roundId',
  path: '/defense/$roundId',
  getParentRoute: () => appAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/project-enrollment': typeof appAppProjectEnrollmentRouteWithChildren
  '/schedule': typeof appAppScheduleRoute
  '/thesis-process': typeof appAppThesisProcessRouteWithChildren
  '/login': typeof authAuthLoginRoute
  '/': typeof appAppIndexRoute
  '/defense/$roundId': typeof appAppDefenseRoundIdRoute
  '/project-enrollment/$roundId': typeof appAppProjectEnrollmentRoundIdRoute
  '/thesis-process/$processId': typeof appAppThesisProcessProcessIdRoute
  '/project-enrollment/': typeof appAppProjectEnrollmentIndexRoute
  '/thesis-process/': typeof appAppThesisProcessIndexRoute
}
export interface FileRoutesByTo {
  '/schedule': typeof appAppScheduleRoute
  '/login': typeof authAuthLoginRoute
  '/': typeof appAppIndexRoute
  '/defense/$roundId': typeof appAppDefenseRoundIdRoute
  '/project-enrollment/$roundId': typeof appAppProjectEnrollmentRoundIdRoute
  '/thesis-process/$processId': typeof appAppThesisProcessProcessIdRoute
  '/project-enrollment': typeof appAppProjectEnrollmentIndexRoute
  '/thesis-process': typeof appAppThesisProcessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(app)/_app/project-enrollment': typeof appAppProjectEnrollmentRouteWithChildren
  '/(app)/_app/schedule': typeof appAppScheduleRoute
  '/(app)/_app/thesis-process': typeof appAppThesisProcessRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(app)/_app/': typeof appAppIndexRoute
  '/(app)/_app/defense/$roundId': typeof appAppDefenseRoundIdRoute
  '/(app)/_app/project-enrollment/$roundId': typeof appAppProjectEnrollmentRoundIdRoute
  '/(app)/_app/thesis-process/$processId': typeof appAppThesisProcessProcessIdRoute
  '/(app)/_app/project-enrollment/': typeof appAppProjectEnrollmentIndexRoute
  '/(app)/_app/thesis-process/': typeof appAppThesisProcessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/project-enrollment'
    | '/schedule'
    | '/thesis-process'
    | '/login'
    | '/'
    | '/defense/$roundId'
    | '/project-enrollment/$roundId'
    | '/thesis-process/$processId'
    | '/project-enrollment/'
    | '/thesis-process/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/schedule'
    | '/login'
    | '/'
    | '/defense/$roundId'
    | '/project-enrollment/$roundId'
    | '/thesis-process/$processId'
    | '/project-enrollment'
    | '/thesis-process'
  id:
    | '__root__'
    | '/(app)/_app'
    | '/(auth)/_auth'
    | '/(app)/_app/project-enrollment'
    | '/(app)/_app/schedule'
    | '/(app)/_app/thesis-process'
    | '/(auth)/_auth/login'
    | '/(app)/_app/'
    | '/(app)/_app/defense/$roundId'
    | '/(app)/_app/project-enrollment/$roundId'
    | '/(app)/_app/thesis-process/$processId'
    | '/(app)/_app/project-enrollment/'
    | '/(app)/_app/thesis-process/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/': {
      id: '/(app)/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAppIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(app)/_app/thesis-process': {
      id: '/(app)/_app/thesis-process'
      path: '/thesis-process'
      fullPath: '/thesis-process'
      preLoaderRoute: typeof appAppThesisProcessRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/schedule': {
      id: '/(app)/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof appAppScheduleRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/project-enrollment': {
      id: '/(app)/_app/project-enrollment'
      path: '/project-enrollment'
      fullPath: '/project-enrollment'
      preLoaderRoute: typeof appAppProjectEnrollmentRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/thesis-process/': {
      id: '/(app)/_app/thesis-process/'
      path: '/'
      fullPath: '/thesis-process/'
      preLoaderRoute: typeof appAppThesisProcessIndexRouteImport
      parentRoute: typeof appAppThesisProcessRoute
    }
    '/(app)/_app/project-enrollment/': {
      id: '/(app)/_app/project-enrollment/'
      path: '/'
      fullPath: '/project-enrollment/'
      preLoaderRoute: typeof appAppProjectEnrollmentIndexRouteImport
      parentRoute: typeof appAppProjectEnrollmentRoute
    }
    '/(app)/_app/thesis-process/$processId': {
      id: '/(app)/_app/thesis-process/$processId'
      path: '/$processId'
      fullPath: '/thesis-process/$processId'
      preLoaderRoute: typeof appAppThesisProcessProcessIdRouteImport
      parentRoute: typeof appAppThesisProcessRoute
    }
    '/(app)/_app/project-enrollment/$roundId': {
      id: '/(app)/_app/project-enrollment/$roundId'
      path: '/$roundId'
      fullPath: '/project-enrollment/$roundId'
      preLoaderRoute: typeof appAppProjectEnrollmentRoundIdRouteImport
      parentRoute: typeof appAppProjectEnrollmentRoute
    }
    '/(app)/_app/defense/$roundId': {
      id: '/(app)/_app/defense/$roundId'
      path: '/defense/$roundId'
      fullPath: '/defense/$roundId'
      preLoaderRoute: typeof appAppDefenseRoundIdRouteImport
      parentRoute: typeof appAppRoute
    }
  }
}

interface appAppProjectEnrollmentRouteChildren {
  appAppProjectEnrollmentRoundIdRoute: typeof appAppProjectEnrollmentRoundIdRoute
  appAppProjectEnrollmentIndexRoute: typeof appAppProjectEnrollmentIndexRoute
}

const appAppProjectEnrollmentRouteChildren: appAppProjectEnrollmentRouteChildren =
  {
    appAppProjectEnrollmentRoundIdRoute: appAppProjectEnrollmentRoundIdRoute,
    appAppProjectEnrollmentIndexRoute: appAppProjectEnrollmentIndexRoute,
  }

const appAppProjectEnrollmentRouteWithChildren =
  appAppProjectEnrollmentRoute._addFileChildren(
    appAppProjectEnrollmentRouteChildren,
  )

interface appAppThesisProcessRouteChildren {
  appAppThesisProcessProcessIdRoute: typeof appAppThesisProcessProcessIdRoute
  appAppThesisProcessIndexRoute: typeof appAppThesisProcessIndexRoute
}

const appAppThesisProcessRouteChildren: appAppThesisProcessRouteChildren = {
  appAppThesisProcessProcessIdRoute: appAppThesisProcessProcessIdRoute,
  appAppThesisProcessIndexRoute: appAppThesisProcessIndexRoute,
}

const appAppThesisProcessRouteWithChildren =
  appAppThesisProcessRoute._addFileChildren(appAppThesisProcessRouteChildren)

interface appAppRouteChildren {
  appAppProjectEnrollmentRoute: typeof appAppProjectEnrollmentRouteWithChildren
  appAppScheduleRoute: typeof appAppScheduleRoute
  appAppThesisProcessRoute: typeof appAppThesisProcessRouteWithChildren
  appAppIndexRoute: typeof appAppIndexRoute
  appAppDefenseRoundIdRoute: typeof appAppDefenseRoundIdRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppProjectEnrollmentRoute: appAppProjectEnrollmentRouteWithChildren,
  appAppScheduleRoute: appAppScheduleRoute,
  appAppThesisProcessRoute: appAppThesisProcessRouteWithChildren,
  appAppIndexRoute: appAppIndexRoute,
  appAppDefenseRoundIdRoute: appAppDefenseRoundIdRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
